### ISSUE TITLE
请问裁剪区域因子是怎么来的？

### ISSUE THREAD

**Issue by ghost** [steveyg/AnswerHelper#27]
另外请问`get_box_by_image(img_path, upper_crop_factor)`这个方法的原理是什么？

**Comment by steveyg** [comment]
@koho

**Comment by koho** [comment]
这个方法的原理是确定裁剪区域的上边界和下边界，因为题目区域的左右边界都很窄，一般都不用裁剪。这个方法分别从上下两个方向开始找到第一个白色像素点个数大于80%的图片宽度的y轴位置，从而确定答题区域的上下边界。由于答题区域的上部有计时器和其他无关文字，不同平台这些无关的东西的高度不同，所以可以通过手动设置上部的裁剪百分比来应对不同情形。所以确定了白色答题区域后，从上部裁剪一定百分比，去掉无关的东西，使得得到一个完整答题区域，这个百分比就是裁剪因子。
