### ISSUE TITLE
这个是不是bug？搜索出来是中锋，推荐答案却为大前锋

### ISSUE THREAD

**Issue by wangguozhong** [steveyg/AnswerHelper#29]
11. 篮球比赛中，五号位一般是指？
A.控球后卫  B.大前锋  C.中锋
===================
分析: 所谓"第6人" 一般是指替补选手 1号位 控球后卫 PG point guard 2号位 得分后卫
SG shooting guard 3号位 小前锋 SF small forward 4号位 大前锋 PF power forward 5
号位 中锋 C ...
===================
推荐答案：  大前锋

**Comment by steveyg** [comment]
这里用的是搜狗的api，应该算他们的bug吧哈哈哈
分析那里就是怕答案出错所以增加一点提示

**Comment by wangguozhong** [comment]
噢噢
