### ISSUE TITLE
词频统计一直是0

### ISSUE THREAD

**Issue by CrazyMelody** [steveyg/AnswerHelper#4]
网页中是有词的，但是用count统计的数量一致是0，不知道什么情况

**Comment by steveyg** [comment]
您使用的问题和答案分别是什么呢，好像出现过0但是很少有全是0的情况，我去排查下，或者更换成移动版页面试试

**Comment by CrazyMelody** [comment]
问题是北京首都，答案是北京，纽约，天津，移动版的试过了一样，好像是编码的问题，我把字符串单独提取出来跑了下可以的，还在排查

**Comment by CrazyMelody** [comment]
emmmm.....沙比了，模拟数据格式有问题，导致解析出来的答案带了单引号，所以匹配不上了。。。

**Comment by steveyg** [comment]
哈哈哈...不要在意这些细节
