### ISSUE TITLE
搜狗汪仔的api是不是被屏蔽了？

### ISSUE THREAD

**Issue by qiuzheng520520** [steveyg/AnswerHelper#40]
我用curl命令直接抓取搜狗汪仔api的冲顶大会接口，总是抓取的西瓜的题目，汪仔api是不是被屏蔽了？
curl -X GET http://140.143.49.31/api/ans2 -d "key=cddh&wdcallback=jQuery321007193239172920585_1516186783454&_=1516186784191" -H '"Referer": "http://nb.sa.sogou.com/"' -H '"User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36 Sogousearch/Ios/5.9.7"'

**Comment by steveyg** [comment]
按理说能抓到题目就没问题，冲顶大会我测试下

**Comment by steveyg** [comment]
我测试了下，抓取正常啊

**Comment by qiuzheng520520** [comment]
是的，是我用参数写错了。
