### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by tianyunfei** [steveyg/AnswerHelper#8]
![1515826999 1](https://user-images.githubusercontent.com/19261515/34903730-ca8efa8e-f872-11e7-9be0-599b2f740fd8.jpg)

现在是该做什么？

**Comment by steveyg** [comment]
出现这个其实算是成功了，只是体验不太友好，现在已经修复这个问题，可以更新下代码试试

**Comment by tianyunfei** [comment]
感谢！我试一下

**Comment by tianyunfei** [comment]
![image](https://user-images.githubusercontent.com/19261515/34904145-7e4efd7e-f87a-11e7-8b9f-9f1ede358c8f.png)

现在是啥问题啊 
![image](https://user-images.githubusercontent.com/19261515/34904148-8d86cc40-f87a-11e7-86e2-a669298e9a7d.png)

**Comment by steveyg** [comment]
这个应该是百度ocr使用的不对，可以参考下https://cloud.baidu.com/doc/OCR/OCR-Python-SDK.html

**Comment by tianyunfei** [comment]
可以了 
 之前用pip install aip的 还是应该用baidu-aip  以为没区别。。。
